DROP TABLE IF EXISTS "trades" CASCADE;
DROP TABLE IF EXISTS "user_settings" CASCADE;
DROP TABLE IF EXISTS "goals" CASCADE;
DROP TABLE IF EXISTS "playbooks" CASCADE;
DROP TABLE IF EXISTS "notebooks" CASCADE;
DROP TABLE IF EXISTS "challenges" CASCADE;
DROP TABLE IF EXISTS "users" CASCADE;
